#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
OUT_FILE="${1:-${ROOT_DIR}/tsm}"

parts=(
  "${ROOT_DIR}/src/lib/sessions.sh"
  "${ROOT_DIR}/src/lib/worktree.sh"
  "${ROOT_DIR}/src/lib/panel.sh"
  "${ROOT_DIR}/src/lib/help.sh"
  "${ROOT_DIR}/src/lib/main.sh"
)

for part in "${parts[@]}"; do
  if [ ! -f "$part" ]; then
    echo "Missing source part: $part" >&2
    exit 1
  fi
done

{
  echo '#!/usr/bin/env bash'
  echo '# Generated by scripts/build.sh. Do not edit this file directly.'
  echo
  for part in "${parts[@]}"; do
    cat "$part"
    echo
  done
  echo 'main "$@"'
} > "$OUT_FILE"

chmod +x "$OUT_FILE"

echo "Built ${OUT_FILE}"
